output "region" {
  value = var.aws_region
}

output "vault_addr" {
  description = "Vault API via internal NLB (all unsealed nodes)."
  value       = "https://${local.vault_fqdn}:8200"
}

output "consul_https_addr" {
  description = "Consul HTTPS API / UI via internal NLB."
  value       = "https://${local.consul_fqdn}:8501"
}

output "vault_nodes" {
  value = { for k, v in aws_instance.vault : k => { id = v.id, ip = v.private_ip, az = v.availability_zone, voter = v.tags["Voter"] } }
}

output "consul_nodes" {
  value = { for k, v in aws_instance.consul : k => { id = v.id, ip = v.private_ip, az = v.availability_zone, voter = v.tags["Voter"] } }
}

output "loadgen_instance_ids" {
  value = aws_instance.loadgen[*].id
}

output "monitoring_instance_id" {
  value = try(aws_instance.monitoring[0].id, null)
}

output "perf_bucket" {
  value = aws_s3_bucket.perf.id
}

output "secrets" {
  description = "Secrets Manager IDs (read with `aws secretsmanager get-secret-value`)."
  value = {
    vault_init    = aws_secretsmanager_secret.vault_init.name
    consul_server = aws_secretsmanager_secret.consul_server.name
    consul_client = aws_secretsmanager_secret.consul_client.name
    monitoring    = aws_secretsmanager_secret.monitoring.name
  }
}

output "ca_cert_pem" {
  description = "Transport TLS CA for Vault and Consul servers."
  value       = tls_self_signed_cert.ca.cert_pem
}

output "access" {
  description = "Handy commands (run locally with your AWS profile)."
  value       = <<-EOT
    # Shell on a load generator
    aws ssm start-session --region ${var.aws_region} --target ${try(aws_instance.loadgen[0].id, "<loadgen-id>")}

    # Grafana on http://localhost:3000 (admin / password from the ${aws_secretsmanager_secret.monitoring.name} secret)
    aws ssm start-session --region ${var.aws_region} --target ${try(aws_instance.monitoring[0].id, "<monitoring-id>")} \
      --document-name AWS-StartPortForwardingSession --parameters portNumber=3000,localPortNumber=3000

    # Vault UI on https://localhost:8200 via a load generator
    aws ssm start-session --region ${var.aws_region} --target ${try(aws_instance.loadgen[0].id, "<loadgen-id>")} \
      --document-name AWS-StartPortForwardingSessionToRemoteHost \
      --parameters host=${local.vault_fqdn},portNumber=8200,localPortNumber=8200

    # Vault root token (test environment only)
    aws secretsmanager get-secret-value --region ${var.aws_region} --secret-id ${aws_secretsmanager_secret.vault_init.name} \
      --query SecretString --output text | jq -r .root_token
  EOT
}

output "grafana_url" {
  description = "Public Grafana URL (empty when grafana_public_zone is unset)."
  value       = local.grafana_public ? "https://${local.grafana_fqdn}" : ""
}

output "vault_ui_url" {
  description = "Public Vault UI (empty unless expose_vault_ui)."
  value       = local.vault_public ? "https://${local.vault_public_fqdn}/ui/" : ""
}

output "consul_ui_url" {
  description = "Public Consul UI (empty unless expose_consul_ui)."
  value       = local.consul_public ? "https://${local.consul_public_fqdn}/ui/" : ""
}

# --- Sensitive credentials (all generated by Terraform, so already in state) ----
# Read with: terraform output -raw <name>
# The Vault root token is not here: vault-0 creates it at init time (see the
# `access` output for the SSM route to it).

output "grafana_admin_password" {
  description = "Grafana admin password (user: admin)."
  value       = random_password.grafana_admin.result
  sensitive   = true
}

output "consul_management_token" {
  description = "Consul initial management token (full access)."
  value       = local.consul_tokens["management_secret"]
  sensitive   = true
}

output "consul_perf_token" {
  description = "Consul perf token (read-mostly; write on perf-* services)."
  value       = local.consul_tokens["perf_secret"]
  sensitive   = true
}

output "mesh_root_ca_pem" {
  description = "Offline mesh root CA certificate (trust anchor for service mesh leaf chains)."
  value       = tls_self_signed_cert.mesh_root.cert_pem
}
